/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.arduinoml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AMLStandaloneSetup extends AMLStandaloneSetupGenerated {

	def static void doSetup() {
		new AMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
