/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.arduinoml.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.unice.polytech.dsl.arduinoml.ide.contentassist.antlr.internal.InternalAMLParser;
import fr.unice.polytech.dsl.arduinoml.services.AMLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class AMLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(AMLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, AMLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getSIGNALAccess().getAlternatives(), "rule__SIGNAL__Alternatives");
			builder.put(grammarAccess.getAppAccess().getGroup(), "rule__App__Group__0");
			builder.put(grammarAccess.getAppAccess().getGroup_6(), "rule__App__Group_6__0");
			builder.put(grammarAccess.getAppAccess().getGroup_11(), "rule__App__Group_11__0");
			builder.put(grammarAccess.getAppAccess().getGroup_16(), "rule__App__Group_16__0");
			builder.put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
			builder.put(grammarAccess.getStateAccess().getGroup_6(), "rule__State__Group_6__0");
			builder.put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
			builder.put(grammarAccess.getActionAccess().getGroup_2(), "rule__Action__Group_2__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_3(), "rule__Transition__Group_3__0");
			builder.put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup(), "rule__Actuator__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getAppAccess().getNameAssignment_1(), "rule__App__NameAssignment_1");
			builder.put(grammarAccess.getAppAccess().getBricksAssignment_5(), "rule__App__BricksAssignment_5");
			builder.put(grammarAccess.getAppAccess().getBricksAssignment_6_1(), "rule__App__BricksAssignment_6_1");
			builder.put(grammarAccess.getAppAccess().getBricksAssignment_10(), "rule__App__BricksAssignment_10");
			builder.put(grammarAccess.getAppAccess().getBricksAssignment_11_1(), "rule__App__BricksAssignment_11_1");
			builder.put(grammarAccess.getAppAccess().getStatesAssignment_15(), "rule__App__StatesAssignment_15");
			builder.put(grammarAccess.getAppAccess().getStatesAssignment_16_1(), "rule__App__StatesAssignment_16_1");
			builder.put(grammarAccess.getAppAccess().getInitialAssignment_19(), "rule__App__InitialAssignment_19");
			builder.put(grammarAccess.getStateAccess().getNameAssignment_1(), "rule__State__NameAssignment_1");
			builder.put(grammarAccess.getStateAccess().getActionsAssignment_5(), "rule__State__ActionsAssignment_5");
			builder.put(grammarAccess.getStateAccess().getActionsAssignment_6_1(), "rule__State__ActionsAssignment_6_1");
			builder.put(grammarAccess.getStateAccess().getTransitionAssignment_9(), "rule__State__TransitionAssignment_9");
			builder.put(grammarAccess.getActionAccess().getValueAssignment_2_1(), "rule__Action__ValueAssignment_2_1");
			builder.put(grammarAccess.getActionAccess().getActuatorAssignment_4(), "rule__Action__ActuatorAssignment_4");
			builder.put(grammarAccess.getTransitionAccess().getValueAssignment_3_1(), "rule__Transition__ValueAssignment_3_1");
			builder.put(grammarAccess.getTransitionAccess().getSensorAssignment_5(), "rule__Transition__SensorAssignment_5");
			builder.put(grammarAccess.getTransitionAccess().getNextAssignment_7(), "rule__Transition__NextAssignment_7");
			builder.put(grammarAccess.getSensorAccess().getNameAssignment_2(), "rule__Sensor__NameAssignment_2");
			builder.put(grammarAccess.getSensorAccess().getPinAssignment_5(), "rule__Sensor__PinAssignment_5");
			builder.put(grammarAccess.getActuatorAccess().getNameAssignment_2(), "rule__Actuator__NameAssignment_2");
			builder.put(grammarAccess.getActuatorAccess().getPinAssignment_5(), "rule__Actuator__PinAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private AMLGrammarAccess grammarAccess;

	@Override
	protected InternalAMLParser createParser() {
		InternalAMLParser result = new InternalAMLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public AMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
