/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.arduinoml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ArduinoMLRuntimeModule extends AbstractArduinoMLRuntimeModule {
}
