/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.arduinoml.parser.antlr;

import com.google.inject.Inject;
import fr.unice.polytech.dsl.arduinoml.parser.antlr.internal.InternalAMLParser;
import fr.unice.polytech.dsl.arduinoml.services.AMLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AMLParser extends AbstractAntlrParser {

	@Inject
	private AMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAMLParser createParser(XtextTokenStream stream) {
		return new InternalAMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "App";
	}

	public AMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
