/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.arduinoml.parser.antlr;

import com.google.inject.Inject;
import fr.unice.polytech.dsl.arduinoml.parser.antlr.internal.InternalArduinoMLParser;
import fr.unice.polytech.dsl.arduinoml.services.ArduinoMLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ArduinoMLParser extends AbstractAntlrParser {

	@Inject
	private ArduinoMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalArduinoMLParser createParser(XtextTokenStream stream) {
		return new InternalArduinoMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Action";
	}

	public ArduinoMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ArduinoMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
