/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.arduinoml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractArduinoMLScopeProvider extends DelegatingScopeProvider {
}
