/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.dsl.arduinoml.formatting2

import com.google.inject.Inject
import fr.unice.polytech.dsl.arduinoml.services.ArduinoMLGrammarAccess
import org.eclipse.xtext.formatting2.AbstractFormatter2

abstract class ArduinoMLFormatter extends AbstractFormatter2 {
	
	@Inject extension ArduinoMLGrammarAccess
	
	// TODO: implement for 
}
